// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pocket/ha/mined_relay.proto

package transport

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MinedRelayMessage is the message format for mined relays transported via Redis Streams
// from the horizontally-scaled Relayer instances to the singleton Miner service.
//
// This message contains all data needed to:
// 1. Deduplicate relays (via relay_hash)
// 2. Route to correct SMST (via session_id, supplier_operator_address)
// 3. Aggregate into session tree (via relay_bytes, compute_units_per_relay)
type MinedRelayMessage struct {
	// relay_hash is the SHA256 hash of the serialized relay.
	// Used for deduplication and as the SMST key.
	RelayHash []byte `protobuf:"bytes,1,opt,name=relay_hash,json=relayHash,proto3" json:"relay_hash,omitempty"`
	// relay_bytes is the serialized relay (RelayRequest + RelayResponse).
	// Stored as-is in the SMST as the value.
	RelayBytes []byte `protobuf:"bytes,2,opt,name=relay_bytes,json=relayBytes,proto3" json:"relay_bytes,omitempty"`
	// compute_units_per_relay is the weight of this relay for tokenomics.
	// Used as the SMST weight parameter.
	ComputeUnitsPerRelay uint64 `protobuf:"varint,3,opt,name=compute_units_per_relay,json=computeUnitsPerRelay,proto3" json:"compute_units_per_relay,omitempty"`
	// session_id identifies which session this relay belongs to.
	// Used to route the relay to the correct SessionTree.
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// session_end_height is the block height at which the session ends.
	// Used for session lifecycle management and TTL calculations.
	SessionEndHeight int64 `protobuf:"varint,5,opt,name=session_end_height,json=sessionEndHeight,proto3" json:"session_end_height,omitempty"`
	// supplier_operator_address is the bech32 address of the supplier operator.
	// Used to route the relay to the correct supplier's Redis stream.
	SupplierOperatorAddress string `protobuf:"bytes,6,opt,name=supplier_operator_address,json=supplierOperatorAddress,proto3" json:"supplier_operator_address,omitempty"`
	// service_id is the on-chain service ID this relay was served for.
	// Used for metrics and validation.
	ServiceId string `protobuf:"bytes,7,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// application_address is the bech32 address of the application that sent the relay.
	// Used for deduplication scoping and metrics.
	ApplicationAddress string `protobuf:"bytes,8,opt,name=application_address,json=applicationAddress,proto3" json:"application_address,omitempty"`
	// arrival_block_height is the block height when the relay arrived at the Relayer.
	// Pinned at receipt time to avoid grace period race conditions.
	ArrivalBlockHeight int64 `protobuf:"varint,9,opt,name=arrival_block_height,json=arrivalBlockHeight,proto3" json:"arrival_block_height,omitempty"`
	// published_at_unix_nano is the Unix timestamp (nanoseconds) when the relay was published.
	// Used for latency metrics and debugging.
	PublishedAtUnixNano int64 `protobuf:"varint,10,opt,name=published_at_unix_nano,json=publishedAtUnixNano,proto3" json:"published_at_unix_nano,omitempty"`
	// session_start_height is the block height at which the session started.
	// Used for session lifecycle management and SessionHeader construction.
	SessionStartHeight int64 `protobuf:"varint,11,opt,name=session_start_height,json=sessionStartHeight,proto3" json:"session_start_height,omitempty"`
	// relay_bytes_s2 is relay_bytes compressed with S2 (klauspost/compress/s2, block format).
	// Exactly one of relay_bytes and relay_bytes_s2 is set. The relayer compresses a large relay
	// that shrinks; the miner restores the original bytes right before it uses them, so the hash,
	// the SMST leaf and the proof are computed over the same bytes as an uncompressed relay.
	RelayBytesS2 []byte `protobuf:"bytes,12,opt,name=relay_bytes_s2,json=relayBytesS2,proto3" json:"relay_bytes_s2,omitempty"`
}

func (m *MinedRelayMessage) Reset()         { *m = MinedRelayMessage{} }
func (m *MinedRelayMessage) String() string { return proto.CompactTextString(m) }
func (*MinedRelayMessage) ProtoMessage()    {}
func (*MinedRelayMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94e9428a47077fe, []int{0}
}
func (m *MinedRelayMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MinedRelayMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *MinedRelayMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinedRelayMessage.Merge(m, src)
}
func (m *MinedRelayMessage) XXX_Size() int {
	return m.Size()
}
func (m *MinedRelayMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MinedRelayMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MinedRelayMessage proto.InternalMessageInfo

func (m *MinedRelayMessage) GetRelayHash() []byte {
	if m != nil {
		return m.RelayHash
	}
	return nil
}

func (m *MinedRelayMessage) GetRelayBytes() []byte {
	if m != nil {
		return m.RelayBytes
	}
	return nil
}

func (m *MinedRelayMessage) GetComputeUnitsPerRelay() uint64 {
	if m != nil {
		return m.ComputeUnitsPerRelay
	}
	return 0
}

func (m *MinedRelayMessage) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *MinedRelayMessage) GetSessionEndHeight() int64 {
	if m != nil {
		return m.SessionEndHeight
	}
	return 0
}

func (m *MinedRelayMessage) GetSupplierOperatorAddress() string {
	if m != nil {
		return m.SupplierOperatorAddress
	}
	return ""
}

func (m *MinedRelayMessage) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *MinedRelayMessage) GetApplicationAddress() string {
	if m != nil {
		return m.ApplicationAddress
	}
	return ""
}

func (m *MinedRelayMessage) GetArrivalBlockHeight() int64 {
	if m != nil {
		return m.ArrivalBlockHeight
	}
	return 0
}

func (m *MinedRelayMessage) GetPublishedAtUnixNano() int64 {
	if m != nil {
		return m.PublishedAtUnixNano
	}
	return 0
}

func (m *MinedRelayMessage) GetSessionStartHeight() int64 {
	if m != nil {
		return m.SessionStartHeight
	}
	return 0
}

func (m *MinedRelayMessage) GetRelayBytesS2() []byte {
	if m != nil {
		return m.RelayBytesS2
	}
	return nil
}

func init() {
	proto.RegisterType((*MinedRelayMessage)(nil), "pocket.ha.MinedRelayMessage")
}

func init() { proto.RegisterFile("pocket/ha/mined_relay.proto", fileDescriptor_f94e9428a47077fe) }

var fileDescriptor_f94e9428a47077fe = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x1c, 0xc6, 0x1b, 0x56, 0x06, 0xf1, 0x2a, 0x04, 0x5e, 0xc5, 0x02, 0x88, 0x50, 0x21, 0x0e, 0x3d,
	0x40, 0x03, 0x9b, 0xb8, 0x70, 0x5b, 0x25, 0xa4, 0xed, 0x30, 0x86, 0x32, 0xed, 0xc2, 0xc5, 0x72,
	0xe2, 0xbf, 0x62, 0x2b, 0xa9, 0x6d, 0xd9, 0xce, 0xd8, 0xde, 0x82, 0x67, 0xe0, 0x69, 0x38, 0xee,
	0xb8, 0x23, 0x6a, 0x5f, 0x04, 0xd9, 0x49, 0x58, 0x6f, 0xc9, 0xf7, 0xf3, 0xf7, 0xff, 0x3e, 0xf9,
	0x6f, 0xf4, 0x4a, 0xab, 0xb2, 0x06, 0x97, 0x71, 0x9a, 0xad, 0x84, 0x04, 0x46, 0x0c, 0x34, 0xf4,
	0x66, 0xa1, 0x8d, 0x72, 0x0a, 0xc7, 0x1d, 0x5c, 0x70, 0xfa, 0x72, 0x5a, 0xa9, 0x4a, 0x05, 0x35,
	0xf3, 0x5f, 0xdd, 0x81, 0xb7, 0xbf, 0xc7, 0xe8, 0xd9, 0x99, 0xb7, 0xe5, 0xde, 0x75, 0x06, 0xd6,
	0xd2, 0x0a, 0xf0, 0x6b, 0x84, 0xc2, 0x14, 0xc2, 0xa9, 0xe5, 0x49, 0x34, 0x8b, 0xe6, 0x93, 0x3c,
	0x0e, 0xca, 0x09, 0xb5, 0x1c, 0xbf, 0x41, 0x7b, 0x1d, 0x2e, 0x6e, 0x1c, 0xd8, 0xe4, 0x41, 0xe0,
	0x9d, 0x63, 0xe9, 0x15, 0xfc, 0x19, 0x1d, 0x94, 0x6a, 0xa5, 0x5b, 0x07, 0xa4, 0x95, 0xc2, 0x59,
	0xa2, 0xc1, 0x74, 0xbd, 0x92, 0x9d, 0x59, 0x34, 0x1f, 0xe7, 0xd3, 0x1e, 0x5f, 0x7a, 0xfa, 0x1d,
	0x4c, 0x48, 0xf7, 0xb1, 0x16, 0xac, 0x15, 0x4a, 0x12, 0xc1, 0x92, 0xf1, 0x2c, 0x9a, 0xc7, 0x79,
	0xdc, 0x2b, 0xa7, 0x0c, 0xbf, 0x47, 0x78, 0xc0, 0x20, 0x19, 0xe1, 0x20, 0x2a, 0xee, 0x92, 0x87,
	0xb3, 0x68, 0xbe, 0x93, 0x3f, 0xed, 0xc9, 0x57, 0xc9, 0x4e, 0x82, 0x8e, 0xbf, 0xa0, 0x17, 0xb6,
	0xd5, 0xba, 0x11, 0x60, 0x88, 0xd2, 0x60, 0xa8, 0x53, 0x86, 0x50, 0xc6, 0x0c, 0x58, 0x9b, 0xec,
	0x86, 0xd9, 0x07, 0xc3, 0x81, 0xf3, 0x9e, 0x1f, 0x77, 0xb8, 0x2b, 0x62, 0xae, 0x44, 0x09, 0xbe,
	0xc8, 0xa3, 0xa1, 0x48, 0x50, 0x4e, 0x19, 0xce, 0xd0, 0x3e, 0xf5, 0xc6, 0x92, 0x3a, 0x5f, 0x66,
	0x18, 0xfa, 0x38, 0x9c, 0xc3, 0x5b, 0x68, 0x98, 0xf7, 0x11, 0x4d, 0xa9, 0x31, 0xe2, 0x8a, 0x36,
	0xa4, 0x68, 0x54, 0x59, 0x0f, 0xdd, 0xe3, 0xd0, 0x1d, 0xf7, 0x6c, 0xe9, 0x51, 0xdf, 0xfe, 0x08,
	0x3d, 0xd7, 0x6d, 0xd1, 0x08, 0xcb, 0x81, 0x11, 0xea, 0xfc, 0x35, 0x5e, 0x13, 0x49, 0xa5, 0x4a,
	0x50, 0xf0, 0xec, 0xff, 0xa7, 0xc7, 0xee, 0x52, 0x8a, 0xeb, 0x6f, 0x54, 0x2a, 0x1f, 0x33, 0x5c,
	0x90, 0x75, 0xd4, 0xb8, 0x21, 0x66, 0xaf, 0x8b, 0xe9, 0xd9, 0x85, 0x47, 0x7d, 0xcc, 0x3b, 0xf4,
	0x64, 0x6b, 0x93, 0xc4, 0x1e, 0x26, 0x93, 0xb0, 0xcc, 0xc9, 0xfd, 0x32, 0x2f, 0x0e, 0x97, 0xe7,
	0x7f, 0xd6, 0x69, 0x74, 0xbb, 0x4e, 0xa3, 0xbb, 0x75, 0x1a, 0xfd, 0x5d, 0xa7, 0xd1, 0xaf, 0x4d,
	0x3a, 0xba, 0xdd, 0xa4, 0xa3, 0xbb, 0x4d, 0x3a, 0xfa, 0xf1, 0xa9, 0x12, 0x8e, 0xb7, 0xc5, 0xa2,
	0x54, 0xab, 0x4c, 0xab, 0xda, 0x7d, 0x90, 0xe0, 0x7e, 0x2a, 0x53, 0x87, 0x1f, 0xa3, 0x9a, 0x26,
	0xd3, 0x75, 0xe5, 0x9f, 0xa7, 0x33, 0x54, 0x5a, 0xad, 0x8c, 0x2b, 0x76, 0xc3, 0xe3, 0x3b, 0xfa,
	0x17, 0x00, 0x00, 0xff, 0xff, 0x43, 0x0a, 0x84, 0x38, 0xbc, 0x02, 0x00, 0x00,
}

func (m *MinedRelayMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MinedRelayMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MinedRelayMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RelayBytesS2) > 0 {
		i -= len(m.RelayBytesS2)
		copy(dAtA[i:], m.RelayBytesS2)
		i = encodeVarintMinedRelay(dAtA, i, uint64(len(m.RelayBytesS2)))
		i--
		dAtA[i] = 0x62
	}
	if m.SessionStartHeight != 0 {
		i = encodeVarintMinedRelay(dAtA, i, uint64(m.SessionStartHeight))
		i--
		dAtA[i] = 0x58
	}
	if m.PublishedAtUnixNano != 0 {
		i = encodeVarintMinedRelay(dAtA, i, uint64(m.PublishedAtUnixNano))
		i--
		dAtA[i] = 0x50
	}
	if m.ArrivalBlockHeight != 0 {
		i = encodeVarintMinedRelay(dAtA, i, uint64(m.ArrivalBlockHeight))
		i--
		dAtA[i] = 0x48
	}
	if len(m.ApplicationAddress) > 0 {
		i -= len(m.ApplicationAddress)
		copy(dAtA[i:], m.ApplicationAddress)
		i = encodeVarintMinedRelay(dAtA, i, uint64(len(m.ApplicationAddress)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ServiceId) > 0 {
		i -= len(m.ServiceId)
		copy(dAtA[i:], m.ServiceId)
		i = encodeVarintMinedRelay(dAtA, i, uint64(len(m.ServiceId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SupplierOperatorAddress) > 0 {
		i -= len(m.SupplierOperatorAddress)
		copy(dAtA[i:], m.SupplierOperatorAddress)
		i = encodeVarintMinedRelay(dAtA, i, uint64(len(m.SupplierOperatorAddress)))
		i--
		dAtA[i] = 0x32
	}
	if m.SessionEndHeight != 0 {
		i = encodeVarintMinedRelay(dAtA, i, uint64(m.SessionEndHeight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.SessionId) > 0 {
		i -= len(m.SessionId)
		copy(dAtA[i:], m.SessionId)
		i = encodeVarintMinedRelay(dAtA, i, uint64(len(m.SessionId)))
		i--
		dAtA[i] = 0x22
	}
	if m.ComputeUnitsPerRelay != 0 {
		i = encodeVarintMinedRelay(dAtA, i, uint64(m.ComputeUnitsPerRelay))
		i--
		dAtA[i] = 0x18
	}
	if len(m.RelayBytes) > 0 {
		i -= len(m.RelayBytes)
		copy(dAtA[i:], m.RelayBytes)
		i = encodeVarintMinedRelay(dAtA, i, uint64(len(m.RelayBytes)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RelayHash) > 0 {
		i -= len(m.RelayHash)
		copy(dAtA[i:], m.RelayHash)
		i = encodeVarintMinedRelay(dAtA, i, uint64(len(m.RelayHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMinedRelay(dAtA []byte, offset int, v uint64) int {
	offset -= sovMinedRelay(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MinedRelayMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RelayHash)
	if l > 0 {
		n += 1 + l + sovMinedRelay(uint64(l))
	}
	l = len(m.RelayBytes)
	if l > 0 {
		n += 1 + l + sovMinedRelay(uint64(l))
	}
	if m.ComputeUnitsPerRelay != 0 {
		n += 1 + sovMinedRelay(uint64(m.ComputeUnitsPerRelay))
	}
	l = len(m.SessionId)
	if l > 0 {
		n += 1 + l + sovMinedRelay(uint64(l))
	}
	if m.SessionEndHeight != 0 {
		n += 1 + sovMinedRelay(uint64(m.SessionEndHeight))
	}
	l = len(m.SupplierOperatorAddress)
	if l > 0 {
		n += 1 + l + sovMinedRelay(uint64(l))
	}
	l = len(m.ServiceId)
	if l > 0 {
		n += 1 + l + sovMinedRelay(uint64(l))
	}
	l = len(m.ApplicationAddress)
	if l > 0 {
		n += 1 + l + sovMinedRelay(uint64(l))
	}
	if m.ArrivalBlockHeight != 0 {
		n += 1 + sovMinedRelay(uint64(m.ArrivalBlockHeight))
	}
	if m.PublishedAtUnixNano != 0 {
		n += 1 + sovMinedRelay(uint64(m.PublishedAtUnixNano))
	}
	if m.SessionStartHeight != 0 {
		n += 1 + sovMinedRelay(uint64(m.SessionStartHeight))
	}
	l = len(m.RelayBytesS2)
	if l > 0 {
		n += 1 + l + sovMinedRelay(uint64(l))
	}
	return n
}

func sovMinedRelay(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMinedRelay(x uint64) (n int) {
	return sovMinedRelay(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MinedRelayMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMinedRelay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MinedRelayMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MinedRelayMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMinedRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMinedRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelayHash = append(m.RelayHash[:0], dAtA[iNdEx:postIndex]...)
			if m.RelayHash == nil {
				m.RelayHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayBytes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMinedRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMinedRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelayBytes = append(m.RelayBytes[:0], dAtA[iNdEx:postIndex]...)
			if m.RelayBytes == nil {
				m.RelayBytes = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ComputeUnitsPerRelay", wireType)
			}
			m.ComputeUnitsPerRelay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ComputeUnitsPerRelay |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMinedRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMinedRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionEndHeight", wireType)
			}
			m.SessionEndHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SessionEndHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupplierOperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMinedRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMinedRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupplierOperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMinedRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMinedRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMinedRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMinedRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApplicationAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArrivalBlockHeight", wireType)
			}
			m.ArrivalBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ArrivalBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublishedAtUnixNano", wireType)
			}
			m.PublishedAtUnixNano = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PublishedAtUnixNano |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionStartHeight", wireType)
			}
			m.SessionStartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SessionStartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayBytesS2", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMinedRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMinedRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelayBytesS2 = append(m.RelayBytesS2[:0], dAtA[iNdEx:postIndex]...)
			if m.RelayBytesS2 == nil {
				m.RelayBytesS2 = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMinedRelay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMinedRelay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMinedRelay(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMinedRelay
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMinedRelay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMinedRelay
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMinedRelay
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMinedRelay
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMinedRelay        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMinedRelay          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMinedRelay = fmt.Errorf("proto: unexpected end of group")
)
