"""Panel definitions for scripts/dashboards/generate.py.

Seven dashboards, in the order an operator who is paid by this software opens
them: money, then the claims and proofs that bring it, the relays behind them,
the relayer's quality, storage and memory, suppliers and the chain, and the
process internals. Every metric the Go code defines is on a panel or listed in
NOT_CHARTED with a reason; generate.py --check enforces it.

Two conventions hold everywhere:
- A run total is sum(last_over_time(counter[$__range])), not increase(): a
  counter born inside the window is invisible to increase() (docs/METRICS_TRIAGE.md).
- ha_miner_upokt_* are recorded in POKT (the code divides compute units by 1e6),
  so they are shown as POKT and never divided again.
"""

# Metrics deliberately left off every panel.
NOT_CHARTED = {
    # The tx layer counts the same submissions as the miner counters below,
    # without service_id or reason; charting both invites summing them.
    "ha_tx_claims_submitted_total": "same submissions as ha_miner_claims_submitted_total, fewer labels",
    "ha_tx_proofs_submitted_total": "same submissions as ha_miner_proofs_submitted_total, fewer labels",
    "ha_tx_claim_errors_total": "same failures as ha_miner_claim_errors_total, without reason",
    "ha_tx_proof_errors_total": "same failures as ha_miner_proof_errors_total, without reason",
}

POKT = "suffix: POKT"
IDENT = "Identity: 0 means it holds. Read it at the END of a run: mid-run, work inside its window has not reached every counter yet."


def specs(g):
    q, T, R, INC, G, P = g["q"], g["T"], g["R"], g["INC"], g["G"], g["P"]
    stat, ts, table, bar, state, text, row = g["stat"], g["ts"], g["table"], g["bar"], g["state"], g["text"], g["row"]
    GREEN, YELLOW, RED = g["GREEN"], g["YELLOW"], g["RED"]
    ZG = g["ZERO_GOOD"]
    ZGA = g["ZERO_GOOD_ABS"]
    inst = 'instance=~"$instance"'

    def unres(prefix):
        return "(%s - %s)" % (T(prefix + "_unresolved_opened_total"), T(prefix + "_unresolved_resolved_total"))

    money = {
        "file": "01-money.json", "uid": "prm-money", "title": "Relay Miner / 1 Money", "tags": ["money"],
        "desc": "Of what I served, how much is proved and paid, how much waits for the chain, how much is lost, and why.",
        "rows": [
            row("Ledger for the selected range (POKT)",
                stat("Claimed", [T("ha_miner_upokt_claimed_total")], POKT, [(None, "blue")], "POKT in the claims the miner built and sent.", w=5),
                stat("Proved", [T("ha_miner_upokt_proved_total")], POKT, [(None, GREEN)], "POKT whose session ended proved: the money that is paid.", w=5),
                stat("Waiting for the chain", [unres("ha_miner_upokt")], POKT, [(None, GREEN), (1e-9, YELLOW)],
                     "Claimed, and the chain has not answered yet (unresolved opened - resolved). It returns to 0 once every proof window closes.", w=5),
                stat("Lost", [T("ha_miner_upokt_lost_total")], POKT, ZG, "Claimed and will not be paid. Any value above 0 has a reason in the panels below.", w=5),
                stat("Forgone", [T("ha_miner_upokt_forgone_total")], POKT, ZG, "Served but never claimed: it never entered the book.", w=4),
                ),
            row("Does the ledger close?",
                stat("Claimed - proved - lost - waiting", ["%s - %s - %s - %s" % (T("ha_miner_upokt_claimed_total"), T("ha_miner_upokt_proved_total"), T("ha_miner_upokt_lost_total"), unres("ha_miner_upokt"))],
                     POKT, ZGA, IDENT + " A session leaves the book through exactly one door, so the doors sum to what was claimed.", w=8, decimals=6),
                stat("Proved share of claimed", ["%s / %s" % (T("ha_miner_upokt_proved_total"), T("ha_miner_upokt_claimed_total"))], "percentunit",
                     [(None, RED), (0.95, YELLOW), (0.999, GREEN)], "At run end every claimed POKT should be proved.", w=8, nodata="-"),
                stat("Relays claimed / proved", [(T("ha_miner_relays_claimed_total"), "claimed"), (T("ha_miner_relays_proved_total"), "proved")], "short", [(None, "blue")], w=8),
                ),
            row("Why money is lost or forgone",
                ts("Lost by reason (POKT/s)", [(R("ha_miner_upokt_lost_total", "reason"), "{{reason}}")], "short", "Zero on a healthy run.", w=8, stack=True),
                ts("Forgone by reason (POKT/s)", [(R("ha_miner_upokt_forgone_total", "reason"), "{{reason}}")], "short", "Served work that never reached a claim.", w=8, stack=True),
                bar("Claims skipped by reason", [(INC("ha_miner_claims_skipped_total", "reason"), "{{reason}}")], "short",
                    "A skipped claim is a session whose tree was empty or whose reward would not pay its fee.", w=8),
                table("Sessions failed, by supplier, service and reason", [(INC("ha_miner_sessions_failed_total", "supplier,service_id,reason"), "sessions")], "short",
                      "DECOY for loss: proof_tx_error here is a failed ATTEMPT that a retry usually lands. The inclusion outcomes on the Claims and proofs dashboard say what the chain has.", w=24, h=7),
                ),
            row("The volume behind the money",
                ts("Relays: claimed / proved / lost / forgone", [(R("ha_miner_relays_claimed_total"), "claimed"), (R("ha_miner_relays_proved_total"), "proved"),
                    (R("ha_miner_relays_lost_total"), "lost"), (R("ha_miner_relays_forgone_total"), "forgone")], "short", "relays/s", w=8),
                ts("Compute units: claimed / proved / lost / forgone", [(R("ha_miner_compute_units_claimed_total"), "claimed"), (R("ha_miner_compute_units_proved_total"), "proved"),
                    (R("ha_miner_compute_units_lost_total"), "lost"), (R("ha_miner_compute_units_forgone_total"), "forgone")], "short", "compute units/s", w=8),
                ts("Waiting for the chain: relays and compute units", [(unres("ha_miner_relays"), "relays"), (unres("ha_miner_compute_units"), "compute units")], "short",
                   "Opened minus resolved, over the selected range.", w=8),
                ),
            row("Balance and stake now",
                table("Balance and stake by supplier", [
                    (G("ha_miner_supplier_balance_upokt", "max", "supplier") + " / 1e6", "balance (POKT)"),
                    (G("ha_miner_supplier_stake_upokt", "max", "supplier") + " / 1e6", "stake (POKT)"),
                    (G("ha_miner_supplier_balance_health_status", "min", "supplier"), "balance health"),
                    (G("ha_miner_supplier_stake_health_ratio", "min", "supplier"), "stake ratio")], "short",
                    "Balance and stake in POKT. Balance health: 2 ok, 1 warning, 0 critical. Stake ratio: stake over the minimum; below 1.2 a few missed proofs unstake the supplier.", w=16),
                stat("Transactions refused for balance", [INC("ha_tx_insufficient_balance_errors_total")], "short", ZG,
                     "A claim or proof the supplier could not pay the fee for.", w=8, h=8),
                ),
        ],
    }

    pipeline = {
        "file": "02-claims-and-proofs.json", "uid": "prm-claims-proofs", "title": "Relay Miner / 2 Claims and proofs", "tags": ["claims", "proofs"],
        "desc": "Is every claim and proof reaching the chain inside its window?",
        "rows": [
            row("What the chain has (the only signal of a real loss)",
                stat("Claims built - submitted", ["%s - %s" % (T("ha_miner_claims_created_total"), T("ha_miner_claims_submitted_total"))], "short", ZGA, IDENT, w=4),
                stat("Claims found on chain / built", ["%s / %s" % (T("ha_miner_claim_inclusion_outcome_total", 'outcome="on_chain_found"'), T("ha_miner_claims_created_total"))],
                     "percentunit", [(None, RED), (0.99, YELLOW), (0.9999, GREEN)], "Written after asking the chain, so it tells a lost claim from a retried one.", w=5, nodata="-"),
                stat("Claim outcomes other than found", [T("ha_miner_claim_inclusion_outcome_total", 'outcome!="on_chain_found"')], "short", ZG, w=5),
                stat("Proof outcomes other than found", [T("ha_miner_proof_inclusion_outcome_total", 'outcome!="on_chain_found"')], "short", ZG, w=5),
                stat("Proof resends refused", [T("ha_miner_proof_rebroadcasts_total", 'result="error"')], "short", ZG,
                     "Read beside the total resends in the Submissions row; with no resends at all this is empty, not healthy.", w=5),
                ),
            row("Inclusion outcomes",
                ts("Claim outcomes", [(R("ha_miner_claim_inclusion_outcome_total", "outcome"), "{{outcome}}")], "short", w=8, stack=True),
                ts("Proof outcomes", [(R("ha_miner_proof_inclusion_outcome_total", "outcome"), "{{outcome}}")], "short", w=8, stack=True),
                table("Why a claim or proof was missing", [(INC("ha_miner_inclusion_missing_cause_total", "phase,cause"), "count")], "short", w=8),
                bar("Proof rejection diagnosis", [(INC("ha_miner_proof_rejection_diagnosis_total", "cause"), "{{cause}}")], "short",
                    "root_mismatch: the tree we proved from is not the one we claimed.", w=8),
                state("Inclusion read state", [(G("ha_miner_inclusion_read_state", "max", "state"), "{{state}}")], "1 marks the state the reconciler is in; unavailable means it cannot read the chain.", w=16,
                      thr=[(None, "transparent"), (1, "blue")]),
                ),
            row("Submissions",
                ts("Claims: built / submitted / errors", [(R("ha_miner_claims_created_total"), "built"), (R("ha_miner_claims_submitted_total"), "submitted"),
                    (R("ha_miner_claim_errors_total", "reason"), "error {{reason}}")], "short", w=8),
                ts("Proofs: built / submitted / errors", [(R("ha_miner_proofs_created_total"), "built"), (R("ha_miner_proofs_submitted_total"), "submitted"),
                    (R("ha_miner_proof_errors_total", "reason"), "error {{reason}}")], "short", w=8),
                ts("Resends by result", [(R("ha_miner_claim_rebroadcasts_total", "result"), "claim {{result}}"), (R("ha_miner_proof_rebroadcasts_total", "result"), "proof {{result}}")], "short",
                   "window_closed is work lost to the window.", w=8),
                ts("Proofs skipped by reason", [(R("ha_miner_proof_skipped_total", "reason"), "{{reason}}"), (R("ha_tx_proof_not_required_total"), "chain: not required")], "short",
                   "claimed_root_unreadable alone is the deferral working; with proof_window_closed the window ran out.", w=8),
                ts("Proof requirement", [(R("ha_miner_proof_requirement_required_total", "reason"), "required {{reason}}"), (R("ha_miner_proof_requirement_skipped_total"), "not required"),
                    (R("ha_miner_proof_requirement_checks_total"), "checks"), (R("ha_miner_proof_requirement_errors_total", "operation"), "error {{operation}}")], "short",
                   "Checks count decisions, not sessions: not a denominator.", w=8),
                ts("Sessions proved", [(R("ha_miner_sessions_proved_total"), "proved"), (R("ha_miner_sessions_probabilistic_proved_total"), "proved without a proof (probabilistic)")], "short", w=8),
                ),
            row("Timing against the window",
                ts("Blocks into the window at submit (p95)", [(P("ha_miner_claim_submission_latency_blocks", 0.95), "claim"), (P("ha_miner_proof_submission_latency_blocks", 0.95), "proof")], "short",
                   "0 is the block the window opens.", w=8),
                table("Scheduled heights vs the chain", [(G("ha_miner_claim_scheduled_height", "max", "supplier,service_id"), "claim at"), (G("ha_miner_proof_scheduled_height", "max", "supplier,service_id"), "proof at"),
                    (G("ha_miner_current_block_height", "max"), "chain height")], "short", "Latest batch per supplier and service.", w=8),
                ts("Claims sealed at the flush cap / relays admitted unchecked", [(R("ha_miner_claim_flush_capped_total", "service_id"), "flush capped {{service_id}}"),
                    (R("ha_miner_claim_window_open_unchecked_total"), "admitted without the window check")], "short", w=8),
                ),
            row("Transactions",
                ts("Broadcasts and chain rejections", [(R("ha_tx_broadcasts_total"), "broadcasts"), (R("ha_tx_broadcast_rejections_total", "tx_type,codespace,code"), "rejected {{tx_type}} {{codespace}}/{{code}}")], "short",
                   "Any rejection is worth reading: code 30 is a deadline, 18 a malformed transaction.", w=8),
                ts("Broadcast latency p95 / permit wait p95", [(P("ha_tx_broadcast_latency_seconds", 0.95), "broadcast"), (P("ha_tx_permit_wait_seconds", 0.95), "permit wait")], "s", w=8),
                ts("Deadline regime per signed transaction", [(R("ha_tx_timeout_regime_total", "phase,regime"), "{{phase}} {{regime}}")], "short",
                   "Counts SIGNED transactions, not broadcasts.", w=8),
                stat("Transaction connection verified", [G("ha_tx_conn_verified", "min")], "short", [(None, RED), (1, GREEN)], w=4),
                table("Connections verified", [(G("ha_tx_conn_member_verified", "min", "conn"), "verified")], "short", w=8, h=4),
                ts("Permits saturated / probe failures", [(R("ha_tx_permit_saturated_total", "waited"), "saturated waited={{waited}}"), (R("ha_tx_conn_probe_failures_total", "reason"), "probe failed {{reason}}")], "short", w=12, h=4),
                ),
            row("Reconciler and tracking bookkeeping",
                ts("Inclusion entries dropped / abandoned / clear failed / cap unused", [(R("ha_miner_inclusion_entry_dropped_total", "phase,cause"), "dropped {{phase}} {{cause}}"),
                    (R("ha_miner_inclusion_group_abandoned_total", "phase,cause"), "abandoned {{phase}} {{cause}}"), (R("ha_miner_inclusion_clear_failed_total", "phase"), "clear failed {{phase}}"),
                    (R("ha_miner_inclusion_resend_cap_unused_total", "phase"), "cap unused {{phase}}")], "short", w=12),
                ts("Tracking records lost", [(R("ha_miner_tracking_writes_failed_total", "kind,reason"), "write failed {{kind}} {{reason}}"),
                    (R("ha_miner_tracking_outcomes_without_record_total", "kind"), "outcome with no record {{kind}}")], "short",
                   "An outcome with no record is lost for good.", w=12),
                ),
            row("Session state machine",
                ts("Transitions", [(R("ha_miner_session_state_transitions_total", "from_state,to_state"), "{{from_state}} -> {{to_state}}"), (R("ha_miner_sessions_created_total"), "created")], "short", w=12, h=9),
                stat("Transitions never dispatched", [T("ha_miner_session_transitions_undispatched_total")], "short", ZG, "A transition the engine decided and no handler ran: a defect.", w=6, h=4),
                stat("Session store errors", [INC("ha_miner_session_store_errors_total")], "short", ZG, w=6, h=4),
                ts("Blocks behind / transition queue", [(G("ha_miner_session_block_processing_lag", "max", "supplier"), "lag {{supplier}}"), (G("ha_miner_session_transition_queue_depth", "max", "supplier"), "queue {{supplier}}")], "short",
                   "Lag 1 is keeping up. A queue that only grows is an early memory warning.", w=12, h=5),
                ts("Snapshots", [(R("ha_miner_session_snapshots_saved_total"), "saved"), (R("ha_miner_session_snapshots_loaded_total"), "loaded"),
                    (INC("ha_miner_session_snapshots_resumed_at_startup_total", "from_state"), "resumed at start from {{from_state}}"),
                    (INC("ha_miner_session_snapshots_skipped_at_startup_total", "state"), "skipped at start {{state}}")], "short", w=12, h=5),
                ),
        ],
    }

    flow = {
        "file": "03-relay-flow.json", "uid": "prm-relay-flow", "title": "Relay Miner / 3 Relay flow", "tags": ["relays"],
        "desc": "Does every relay the relayer answered reach the tree the claim is built from?",
        "rows": [
            row("Nothing falls between the stages",
                stat("Served - published - skipped - dropped", ["%s - %s - %s - %s" % (T("ha_relayer_relays_served_total"), T("ha_relayer_relays_published_total"),
                     T("ha_relayer_relays_skipped_difficulty_total"), T("ha_relayer_relays_dropped_total"))], "short", ZGA, IDENT, w=6),
                stat("Consumed from stream - added to tree", ["%s - %s" % (T("ha_miner_relays_consumed_from_stream_total"), T("ha_miner_relays_added_to_smst_total"))], "short", ZGA, IDENT, w=6),
                stat("Queued, not on the stream yet", ["%s - %s" % (G("ha_relayer_relays_published_total"), G("ha_transport_published_total"))], "short", [(None, GREEN), (10000, YELLOW)],
                     "Relays the relayer queued that the batch writer has not written. Grows under load, returns to about 0.", w=6),
                stat("Orphaned streams", [G("ha_miner_orphaned_streams", "max")], "short", [(None, GREEN), (1, YELLOW)], "Streams of suppliers no miner owns; counted hourly.", w=6),
                ),
            row("The funnel (relays/s): the lines should lie on each other",
                ts("Received / served / published / on stream / consumed / in tree / acknowledged", [(R("ha_relayer_relays_received_total"), "received"), (R("ha_relayer_relays_served_total"), "served"),
                    (R("ha_relayer_relays_published_total"), "published"), (R("ha_transport_published_total"), "written to stream"), (R("ha_transport_consumed_total"), "read from stream"),
                    (R("ha_miner_relays_consumed_from_stream_total"), "consumed by miner"), (R("ha_miner_relays_added_to_smst_total"), "added to tree"), (R("ha_transport_acked_total"), "acknowledged")],
                   "short", w=16, h=9),
                ts("Skipped by difficulty / target bits", [(R("ha_relayer_relays_skipped_difficulty_total", "service_id"), "skipped {{service_id}}"),
                    (G("ha_query_relay_mining_difficulty_target_bits", "max", "service_id"), "target bits {{service_id}}")], "short",
                   "After the first settlement the difficulty rises and published falls below served by design.", w=8, h=9),
                ts("Claim leaves vs relays counted", [(R("ha_miner_claim_leaves_total"), "leaves"), (R("ha_miner_claim_relay_attempts_total"), "relays counted"),
                    (R("ha_miner_claim_leaf_collapse_total"), "claims that collapsed")], "short",
                   "Identical relay bytes share one leaf: a collapse is work that is not paid.", w=24, h=6),
                ),
            row("Where relays fall out",
                ts("Relayer drops by reason", [(R("ha_relayer_relays_dropped_total", "reason"), "{{reason}}")], "short", "publish_failed is loss; stake_exhausted is work given away.", w=8, stack=True),
                ts("Publisher refused / discarded / errors", [(R("ha_transport_publish_rejected_total", "reason"), "refused {{reason}}"), (R("ha_transport_publish_discarded_total", "reason"), "discarded {{reason}}"),
                    (R("ha_transport_publish_errors_total"), "errors")], "short", w=8),
                ts("Miner rejected / failed / no key", [(R("ha_miner_relays_rejected_total", "reason"), "rejected {{reason}}"), (R("ha_miner_relays_failed_smst_total"), "failed to add to tree"),
                    (R("ha_miner_relays_dropped_no_key_total"), "no key")], "short", "relay_bytes_corrupt* is a producer defect.", w=8),
                ts("Shutdown hand-back", [(R("ha_miner_shutdown_drained_relays_total"), "drained"), (R("ha_miner_shutdown_abandoned_relays_total"), "miner left pending"),
                    (R("ha_transport_shutdown_abandoned_relays_total"), "publisher never wrote")], "short", w=8),
                ts("Consumer group upkeep", [(R("ha_transport_reaped_consumers_total"), "consumers reaped"), (R("ha_transport_reap_destroyed_pending_total"), "pending destroyed (must stay 0)"),
                    (R("ha_transport_reclaim_errors_total", "op"), "reclaim error {{op}}"), (R("ha_transport_claimed_total"), "reclaimed")], "short", w=8),
                ts("Read errors", [(R("ha_transport_deserialization_errors_total"), "deserialization"), (R("ha_transport_consume_errors_total", "error_type"), "consume {{error_type}}")], "short", w=8),
                ),
            row("Deduplication and batches",
                ts("Dedup", [(R("ha_miner_dedup_cache_hits_total"), "hits"), (R("ha_miner_dedup_misses_total"), "misses"), (R("ha_miner_dedup_marked_total"), "marked"), (R("ha_miner_dedup_errors_total"), "errors")], "short", w=8),
                ts("Batches", [(R("ha_miner_relay_batch_flushes_total", "trigger"), "flush {{trigger}}"), (R("ha_miner_relay_batch_released_total", "reason"), "released {{reason}}"),
                    (R("ha_miner_relay_batch_panics_total"), "panics")], "short", w=8),
                ts("Charges that could not be written", [(R("ha_transport_charge_write_failures_total", "reason"), "{{reason}}")], "short", "A charge not written is a relay served and not billed.", w=8),
                ),
            row("Latency across the pipe",
                ts("End to end, relayer to tree (p50 / p95 / p99)", [(P("ha_transport_end_to_end_latency_seconds", q_), "p%d" % int(q_ * 100)) for q_ in (0.5, 0.95, 0.99)], "s", w=8),
                ts("Miner processing p95 by status", [(P("ha_miner_relay_processing_latency_seconds", 0.95, "status_code"), "{{status_code}}")], "s", w=8),
                ts("Batch write to Redis p95 by result", [(P("ha_transport_dispatch_write_duration_seconds", 0.95, "result"), "{{result}}")], "s", w=8),
                ts("Tree store operations", [(R("ha_smst_store_operations_total", "operation,result"), "{{operation}} {{result}}"), (R("ha_smst_store_errors_total", "operation,error_type"), "error {{operation}} {{error_type}}")], "short", w=12),
                ts("Tree store p95 by operation", [(P("ha_smst_store_operation_duration_seconds", 0.95, "operation"), "{{operation}}")], "s", w=12),
                ),
            row("Stream reads and compression",
                ts("Bytes held by consumers", [(G("ha_transport_consumer_channel_bytes", "sum"), "in channel"), (G("ha_transport_consumer_read_reply_bytes", "sum"), "last read reply"),
                    (R("ha_transport_consumer_read_bytes_total"), "read/s")], "bytes", w=8),
                ts("Messages requested per read", [(G("ha_transport_consumer_read_requested_count", "sum"), "requested")], "short", w=8),
                ts("Compression", [("%s / %s" % (R("ha_transport_relay_compression_bytes_total", extra='stage="out"'), R("ha_transport_relay_compression_bytes_total", extra='stage="in"')), "bytes out / in"),
                    (R("ha_transport_relay_compression_total", "outcome"), "{{outcome}}")], "short", "Relays of 16 KiB or more are S2-compressed when that saves at least 10 %.", w=8),
                ),
        ],
    }

    relayer = {
        "file": "04-relayer.json", "uid": "prm-relayer", "title": "Relay Miner / 4 Relayer", "tags": ["relayer"],
        "desc": "Are gateways getting fast, accepted, billed answers, and if not, why?",
        "rows": [
            row("Now",
                stat("Relays served/s", [R("ha_relayer_relays_served_total")], "reqps", [(None, "blue")], w=4),
                stat("Rejected / received", ["%s / %s" % (R("ha_relayer_relays_rejected_total"), R("ha_relayer_relays_received_total"))], "percentunit", [(None, GREEN), (0.01, YELLOW), (0.05, RED)], w=4, nodata="-"),
                stat("Latency p99", [P("ha_relayer_relay_latency_seconds", 0.99)], "s", [(None, GREEN), (0.5, YELLOW), (1, RED)], w=4, nodata="-"),
                stat("Backends up (lowest)", [G("ha_relayer_backend_health_status", "min")], "short", [(None, RED), (1, GREEN)], w=4),
                stat("Served and not billed", [INC("ha_relayer_relay_meter_unbilled_total")], "short", ZG, "A charge that could not be written after an optimistic answer.", w=4),
                stat("Signing keys loaded", [G("ha_relayer_signing_keys_loaded", "max")], "short", [(None, RED), (1, GREEN)], w=4),
                ),
            row("Rejections and failures",
                ts("Rejected by reason", [(R("ha_relayer_relays_rejected_total", "reason"), "{{reason}}")], "reqps",
                   "storage_saturated, publish_queue_full and validation_queue_full are the relayer protecting itself; stake_exhausted is the application out of budget.", w=12, stack=True),
                ts("Validation failures by reason", [(R("ha_relayer_validation_failures_total", "reason"), "{{reason}}")], "reqps", w=12),
                ts("Backend requests by outcome", [(R("ha_relayer_backend_requests_total", "outcome,status_code"), "{{outcome}} {{status_code}}"), (R("ha_relayer_fast_fails_total", "service_id"), "fast fail {{service_id}}"),
                    (R("ha_relayer_backend_missing_total", "rpc_type"), "no backend for rpc_type {{rpc_type}}")], "reqps", w=12),
                ts("Served outside the normal path", [(R("ha_relayer_relays_served_optimistically_total"), "optimistic"), (R("ha_relayer_relays_served_over_budget_total", "reason"), "over budget {{reason}}"),
                    (R("ha_relayer_undeclared_transport_served_total", "rpc_type"), "undeclared transport {{rpc_type}}"), (R("ha_relayer_live_connections_cut_total", "transport"), "live connection cut {{transport}}")], "reqps", w=12),
                ),
            row("Where the time goes (p95)",
                ts("Before the backend / backend / after", [(P("ha_relayer_relay_pre_backend_seconds", 0.95), "before"), (P("ha_relayer_backend_latency_seconds", 0.95), "backend"),
                    (P("ha_relayer_relay_post_backend_seconds", 0.95), "after")], "s", w=8),
                ts("Validation / meter by mode", [(P("ha_relayer_validation_latency_seconds", 0.95, "mode"), "validation {{mode}}"), (P("ha_relayer_relay_meter_latency_seconds", 0.95, "mode"), "meter {{mode}}")], "s", w=8),
                ts("Connection pool wait / dial", [(P("ha_relayer_http_pool_wait_seconds", 0.95), "pool wait"), (P("ha_relayer_backend_dial_seconds", 0.95), "dial")], "s", w=8),
                ts("Backend pool in use", [("%s / %s" % (G("ha_relayer_http_pool_in_flight", "sum", "service_id"), G("ha_relayer_http_pool_max_conns", "sum", "service_id")), "{{service_id}}")], "percentunit",
                   "Above 0.8 the pool is the bottleneck: size it with scripts/loadtest.", w=8),
                ts("Connections reused", [(R("ha_relayer_backend_conn_reused_total", "reused"), "reused={{reused}}")], "short", w=8),
                ts("Worker pools", [(G("ha_relayer_worker_pool_max_workers", "max", "subpool"), "max {{subpool}}"), (G("ha_relayer_worker_queue_depth", "max", "subpool"), "waiting {{subpool}}")], "short", w=8),
                ),
            row("Metering",
                ts("Charges by result", [(R("ha_relayer_relay_meter_consumptions_total", "result"), "{{result}}"), (R("ha_relayer_relay_meter_errors_total", "operation"), "error {{operation}}")], "short", w=8),
                ts("Sessions metered", [(G("ha_relayer_relay_meter_sessions_active", "sum", "service_id"), "{{service_id}}")], "short", w=8),
                ts("Difficulty lookups that failed", [(R("ha_relayer_difficulty_query_failures_total", "service_id"), "{{service_id}}")], "short", "The relay is still served: it fails open.", w=8),
                ),
            row("Transports",
                ts("WebSocket", [(G("ha_relayer_websocket_connections_active", "sum"), "open"), (R("ha_relayer_websocket_connections_total"), "opened/s"),
                    (R("ha_relayer_websocket_messages_forwarded_total", "direction"), "messages {{direction}}")], "short", w=8),
                ts("WebSocket closes", [(R("ha_relayer_websocket_closes_total", "close_code,initiated_by"), "{{close_code}} by {{initiated_by}}")], "short", "1013 is the relayer closing under pressure.", w=8),
                ts("Requests by protocol / open connections", [(R("ha_relayer_inbound_requests_by_proto_total", "proto"), "{{proto}}"), (G("ha_relayer_active_connections", "sum"), "open connections"),
                    (R("ha_relayer_grpc_web_requests_total"), "gRPC-Web")], "short", w=8),
                ts("Streaming", [(R("ha_relayer_streaming_chunks_forwarded_total"), "chunks"), (R("ha_relayer_streaming_batches_signed_total"), "batches signed"),
                    (R("ha_relayer_streaming_bytes_forwarded_total"), "bytes")], "short", w=8),
                ts("Body size p95", [(P("ha_relayer_request_body_size_bytes", 0.95), "request"), (P("ha_relayer_response_body_size_bytes", 0.95), "response")], "bytes", w=8),
                ts("Backend health checks", [(R("ha_relayer_health_check_successes_total", "service_id"), "ok {{service_id}}"), (R("ha_relayer_health_check_failures_total", "service_id,endpoint"), "failed {{service_id}}")], "short", w=8),
                ),
            row("Simulated relays (never billed)",
                ts("Simulated relays by result", [(R("ha_relayer_simulated_relays_total", "result"), "{{result}}")], "short", w=12),
                ts("Simulated relay p95", [(P("ha_relayer_simulated_relay_duration_seconds", 0.95, "transport"), "{{transport}}")], "s", w=12),
                ),
        ],
    }

    storage = {
        "file": "05-storage-and-memory.json", "uid": "prm-storage", "title": "Relay Miner / 5 Storage and memory", "tags": ["redis", "memory"],
        "desc": "Is Redis or process memory what is throttling me?",
        "rows": [
            row("Admission gates",
                stat("Every gate open", [G("ha_transport_store_operable", "min")], "short", [(None, RED), (1, GREEN)],
                     "0 means a gate is closed: the relayer refuses new work, or the miner pauses ingestion, until Redis has room again.", w=6),
                stat("Redis free (lowest seen by a process)", [G("ha_transport_store_free_bytes", "min")], "bytes", [(None, RED), (1073741824, YELLOW), (1610612736, GREEN)],
                     "Gates close below 1 GiB free (or 1/8 of maxmemory if smaller) and reopen 512 MiB / 1 GiB above that.", w=6),
                state("Gate state", [(G("ha_transport_store_operable", "min", "component,gate"), "{{component}} {{gate}}")], w=12, h=4),
                ts("Seconds closed by gate and reason", [("%s / count by (component,gate,reason)(%s)" % (INC("ha_transport_store_closed_seconds_total", "component,gate,reason"), q("ha_transport_store_closed_seconds_total")),
                    "{{component}} {{gate}} {{reason}}")], "s", "Divided by the number of series of each gate: each process reports its own.", w=12),
                ts("Gate transitions", [(R("ha_transport_store_transitions_total", "component,gate,state,reason"), "{{component}} {{gate}} {{state}} {{reason}}")], "short", w=12),
                ),
            row("Redis memory",
                ts("Used vs maxmemory (miner leader's view)", [(G("ha_miner_redis_used_memory_bytes", "max"), "used"), (G("ha_miner_redis_max_memory_bytes", "max"), "maxmemory")], "bytes", w=8),
                stat("Used / maxmemory", [G("ha_miner_redis_memory_usage_ratio", "max")], "percentunit", [(None, GREEN), (0.7, YELLOW), (0.85, RED)], w=4, h=8),
                bar("Memory by key family (at the last close)", [(G("ha_miner_store_memory_at_close_bytes", "max", "family"), "{{family}}")], "bytes", w=12),
                ),
            row("Redis from the client side",
                ts("Command latency p95", [(P("ha_transport_redis_command_seconds", 0.95, "component,command"), "{{component}} {{command}}")], "s", w=12),
                ts("Pool connections", [(G("ha_transport_redis_pool_total_conns", "sum", "component"), "total {{component}}"), (G("ha_transport_redis_pool_idle_conns", "sum", "component"), "idle {{component}}"),
                    (G("ha_transport_redis_pool_size_effective", "max", "component"), "size {{component}}"), (G("ha_transport_redis_pool_pools", "max", "component"), "pools {{component}}")], "short", w=12),
                ts("Waiting for a connection", [(G("ha_transport_redis_pool_pending_requests", "sum", "component"), "waiting {{component}}"), (G("ha_transport_redis_pool_pending_requests_max", "max", "component"), "worst pool {{component}}"),
                    (R("ha_transport_redis_pool_timeouts_total", "component"), "timeouts/s {{component}}"), (G("ha_transport_redis_pool_timeout_seconds_effective", "max", "component"), "timeout s {{component}}")], "short",
                   "Read with timeouts: the wait improves when timeouts start, because a timed-out wait is not counted.", w=12),
                ts("Pool hits / misses / waits", [(R("ha_transport_redis_pool_hits_total", "component"), "hit {{component}}"), (R("ha_transport_redis_pool_misses_total", "component"), "miss {{component}}"),
                    (R("ha_transport_redis_pool_wait_count_total", "component"), "waits {{component}}"),
                    ("%s / %s" % (R("ha_transport_redis_pool_wait_seconds_total", "component"), R("ha_transport_redis_pool_wait_count_total", "component")), "mean wait s {{component}}"),
                    (R("ha_transport_redis_pool_stale_conns_total", "component"), "stale {{component}}"), (R("ha_transport_redis_pool_unusable_total", "component"), "unusable {{component}}")], "short", w=12),
                ts("Reconnections", [(R("ha_transport_reconnection_attempts_total", "component"), "attempts {{component}}"), (R("ha_transport_reconnection_success_total", "component"), "succeeded {{component}}")], "short", w=12),
                ),
            row("Process memory",
                ts("Resident memory by process", [('max by (instance)(process_resident_memory_bytes{job=~"relayers|miners",%s})' % inst, "{{instance}}")], "bytes",
                   "Resident memory is about twice the live heap. Compare it with the container or unit limit.", w=8),
                ts("Heap in use", [(G("ha_runtime_heap_inuse_bytes", "max", "instance", inst), "{{instance}}")], "bytes", w=8),
                ts("Ingestion brake / forced GC", [(G("ha_miner_ingestion_memory_brake_closed", "max"), "brake closed"), (R("ha_miner_ingestion_memory_brake_transitions_total", "state"), "brake {{state}}"),
                    (R("ha_miner_forced_gc_total", "reason"), "forced GC {{reason}}")], "short", "The miner pauses reading relays near its memory limit.", w=8),
                ),
            row("Claim trees in memory",
                ts("Pending leaf bytes / trees unloaded", [(G("ha_smst_pending_leaf_bytes", "sum"), "pending leaf bytes"), (R("ha_miner_smst_trees_unloaded_total"), "trees unloaded/s")], "short", w=8),
                ts("Compaction and rebuild", [(R("ha_smst_leaves_compacted_total"), "leaves compacted"), (R("ha_smst_cold_compactions_total", "result"), "compactions {{result}}"),
                    (R("ha_smst_cold_rebuilds_total", "result"), "rebuilds {{result}}"), (R("ha_smst_cold_compaction_bytes_total", "kind"), "bytes {{kind}}")], "short", w=8),
                ts("Compaction / rebuild p95", [(P("ha_smst_cold_duration_seconds", 0.95, "operation"), "{{operation}}")], "s", w=8),
                ts("Proofs waiting for memory", [(G("ha_smst_rebuild_waiting", "max", "kind"), "waiting {{kind}}"), (G("ha_smst_rebuild_oldest_proof_wait_seconds", "max"), "oldest wait s"),
                    (P("ha_smst_rebuild_wait_seconds", 0.95, "kind"), "wait p95 {{kind}}")], "short", "A proof that waits past its window is lost.", w=12),
                ts("Rebuild heap growth over estimate (p95)", [(P("ha_smst_rebuild_heap_growth_over_estimate", 0.95, "kind"), "{{kind}}")], "short", w=12),
                ts("Tree corruption and panics", [(R("ha_smst_corruption_evictions_total", "reason"), "evicted {{reason}}"), (R("ha_smst_corruption_purged_total", "reason"), "purged {{reason}}"),
                    (R("ha_smst_panics_recovered_total", "operation"), "panic {{operation}}"), (R("ha_miner_smst_exit_checkpoint_failed_total"), "exit checkpoint failed")], "short", "All of these stay at 0.", w=24, h=6),
                ),
            row("Relayer buffers",
                ts("Validation queue used", [("%s / %s" % (G("ha_relayer_validation_queue_bytes", "sum", "service_id"), G("ha_relayer_validation_queue_max_bytes", "sum", "service_id")), "{{service_id}}")], "percentunit",
                   "At 1 the relayer answers 429 for that service.", w=12),
                ts("Publish and batch queues", [(G("ha_relayer_publish_queue_bytes", "sum"), "publish queue"), (G("ha_relayer_batch_queue_bytes", "sum"), "batch queue")], "bytes",
                   "Over redis.batch_max_queued_mib new relays are refused.", w=12),
                ),
        ],
    }

    chain = {
        "file": "06-suppliers-and-chain.json", "uid": "prm-suppliers-chain", "title": "Relay Miner / 6 Suppliers and chain", "tags": ["suppliers", "chain"],
        "desc": "Stake, balance, keys, leadership and the chain clock: will the next claim be accepted?",
        "rows": [
            row("Supplier alerts",
                ts("Balance and stake alerts", [(R("ha_miner_supplier_balance_critical_alerts_total", "supplier"), "balance critical {{supplier}}"), (R("ha_miner_supplier_balance_warning_alerts_total", "supplier"), "balance warning {{supplier}}"),
                    (R("ha_miner_supplier_stake_critical_alerts_total", "supplier"), "stake critical {{supplier}}"), (R("ha_miner_supplier_stake_warning_alerts_total", "supplier"), "stake warning {{supplier}}")], "short", w=12),
                ts("Monitor errors", [(R("ha_miner_supplier_monitor_errors_total", "error_type"), "{{error_type}}")], "short", w=12),
                ),
            row("Suppliers across miners",
                stat("Suppliers active", [G("ha_miner_supplier_manager_suppliers_active", "max")], "short", [(None, "blue")], w=4),
                ts("Claimed vs fair share by miner", [('max by (instance)(%s)' % q("ha_miner_supplier_claimed_count"), "claimed {{instance}}"), ('max by (instance)(%s)' % q("ha_miner_supplier_fair_share"), "fair share {{instance}}")], "short",
                   "A miner holding more than its share for minutes means a rebalance is stuck.", w=10),
                ts("Leases", [(R("ha_miner_supplier_claimed_total"), "claimed"), (R("ha_miner_supplier_released_total"), "released"), (R("ha_miner_supplier_lease_lost_total", "trigger"), "lost {{trigger}}"),
                    (R("ha_miner_supplier_drain_lease_overrun_total", "trigger"), "drain overran lease {{trigger}}")], "short", w=10),
                ts("Drain decisions / registry / cache", [(R("ha_miner_supplier_drain_decision_total", "drain_reason,on_chain_result"), "drain {{drain_reason}} {{on_chain_result}}"),
                    (R("ha_miner_supplier_registry_updates_total", "action"), "registry {{action}}"), (R("ha_miner_supplier_cache_write_skipped_total", "reason"), "cache write skipped {{reason}}"),
                    (R("ha_cache_supplier_contaminated_total", "source"), "contaminated {{source}}"), (R("ha_miner_supplier_boot_services_fallback_total"), "boot services fallback")], "short",
                   "A steady boot services fallback means block events are not flowing.", w=24),
                ),
            row("Leadership",
                stat("Leaders (must be 1)", ["sum(%s)" % q("ha_miner_leader_status")], "short", [(None, RED), (1, GREEN), (2, RED)], w=4),
                state("Leader by miner", [('max by (instance)(%s)' % q("ha_miner_leader_status"), "{{instance}}")], w=10, thr=[(None, "transparent"), (1, GREEN)]),
                ts("Elections / losses / failures", [(R("ha_miner_leader_elections_total"), "elections"), (R("ha_miner_leader_losses_total"), "losses"),
                    (R("ha_miner_leader_acquisition_failures_total", "reason"), "failed {{reason}}"), (G("ha_cache_orchestrator_leader_status", "max"), "cache orchestrator leader")], "short", w=10),
                ),
            row("Chain clock",
                ts("Block height seen by each process", [(G("ha_miner_current_block_height", "max"), "miner"), (G("ha_relayer_current_block_height", "max"), "relayer"), (G("ha_cache_current_block_height", "max"), "cache")], "short",
                   "The three lines stay within a block of each other.", w=8),
                ts("Block interval vs configured", [(G("ha_miner_current_block_interval_seconds", "max"), "measured"), (G("ha_miner_configured_block_time_seconds", "max"), "configured")], "s",
                   "Measured by the leader. Above 1.5x configured the node is slow.", w=8),
                ts("Slow blocks", [(R("ha_miner_fullnode_slow_blocks_total"), "slow blocks/s"), (G("ha_miner_fullnode_slow_blocks_consecutive", "max"), "consecutive")], "short", w=8),
                ts("Block events", [(R("ha_cache_block_events_published_total"), "published"), (R("ha_cache_block_events_received_total"), "received"),
                    (R("ha_cache_block_events_ignored_total", "reason"), "ignored {{reason}}"), (R("ha_cache_block_events_dropped_total", "channel"), "dropped {{channel}}")], "short",
                   "A dropped event is a consumer too slow to keep up.", w=24, h=6),
                ),
            row("Keys",
                stat("Keys loaded: miner vs relayer", [(G("ha_keys_supplier_keys_active", "max"), "key source"), (G("ha_relayer_signing_keys_loaded", "max"), "relayer signing")], "short", [(None, "blue")], w=6),
                stat("Seconds since the last key reload", ["time() - %s" % G("ha_keys_last_successful_reload_timestamp_seconds", "max")], "s", [(None, GREEN), (600, YELLOW)], w=6, nodata="-"),
                ts("Key reloads and errors", [(R("ha_keys_reloads_total"), "reloads"), (R("ha_keys_changes_total", "type"), "changes {{type}}"), (R("ha_keys_load_errors_total", "provider"), "load error {{provider}}"),
                    (G("ha_keys_undecodable_records", "max", "provider"), "undecodable {{provider}}"), (R("ha_keys_keyring_cache_discarded_total", "provider"), "keyring cache discarded {{provider}}")], "short", w=12),
                ),
        ],
    }

    internals = {
        "file": "07-process-internals.json", "uid": "prm-internals", "title": "Relay Miner / 7 Process internals", "tags": ["internals"],
        "desc": "Where inside the binaries time and memory go. Open it when another dashboard points here.",
        "rows": [
            row("Go runtime (per process)",
                ts("Goroutines and threads", [(G("ha_runtime_goroutines", "max", "instance", inst), "goroutines {{instance}}"), (G("ha_runtime_threads", "max", "instance", inst), "threads {{instance}}")], "short", w=8),
                ts("Heap", [(G("ha_runtime_heap_alloc_bytes", "max", "instance", inst), "alloc {{instance}}"), (G("ha_runtime_heap_sys_bytes", "max", "instance", inst), "sys {{instance}}"),
                    (G("ha_runtime_heap_idle_bytes", "max", "instance", inst), "idle {{instance}}"), (G("ha_runtime_heap_released_bytes", "max", "instance", inst), "released {{instance}}"),
                    (G("ha_runtime_next_gc_heap_size_bytes", "max", "instance", inst), "next GC {{instance}}")], "bytes", w=8),
                ts("Stacks and objects", [(G("ha_runtime_stack_inuse_bytes", "max", "instance", inst), "stack in use {{instance}}"), (G("ha_runtime_stack_sys_bytes", "max", "instance", inst), "stack sys {{instance}}"),
                    (G("ha_runtime_heap_objects", "max", "instance", inst), "objects {{instance}}")], "short", w=8),
                ts("Allocation rate", [(R("ha_runtime_mallocs_total", "instance", inst), "mallocs {{instance}}"), (R("ha_runtime_frees_total", "instance", inst), "frees {{instance}}")], "short", w=8),
                ts("GC", [(R("ha_runtime_gc_completed_total", "instance", inst), "GCs/s {{instance}}"), (R("ha_runtime_gc_forced_total", "instance", inst), "forced/s {{instance}}"),
                    ("%s / 1e9" % R("ha_runtime_gc_pause_total_nanoseconds", "instance", inst), "pause s/s {{instance}}"), (G("ha_runtime_gc_cpu_fraction", "max", "instance", inst), "CPU fraction {{instance}}")], "short",
                   "A GC CPU fraction above 0.25 means the process is near its memory limit.", w=8),
                ts("Seconds since the last GC", [("time() - %s" % G("ha_runtime_last_gc_timestamp_seconds", "max", "instance", inst), "{{instance}}")], "s", w=8),
                ts("CPU by process", [('sum by (instance)(rate(process_cpu_seconds_total{job=~"relayers|miners",%s}[$__rate_interval]))' % inst, "{{instance}}")], "short", "Cores used.", w=12),
                ts("Open file descriptors", [('max by (instance)(process_open_fds{job=~"relayers|miners",%s})' % inst, "{{instance}}")], "short", w=12),
                ),
            row("Miner worker pools",
                ts("Workers and waiting tasks", [(G("ha_miner_worker_pool_configured_size", "max", "pool_name"), "size {{pool_name}}"), (G("ha_miner_worker_pool_running_workers", "max", "pool_name"), "running {{pool_name}}"),
                    (G("ha_miner_worker_pool_waiting_tasks", "max", "pool_name"), "waiting {{pool_name}}")], "short", w=12),
                ts("Tasks", [(R("ha_miner_worker_pool_submitted_tasks_total", "pool_name"), "submitted {{pool_name}}"), (R("ha_miner_worker_pool_completed_tasks_total", "pool_name"), "completed {{pool_name}}"),
                    (R("ha_miner_worker_pool_successful_tasks_total", "pool_name"), "ok {{pool_name}}"), (R("ha_miner_worker_pool_failed_tasks_total", "pool_name"), "failed {{pool_name}}"),
                    (R("ha_miner_worker_pool_dropped_tasks_total", "pool_name"), "dropped {{pool_name}}")], "short", "Failed tasks are panics; dropped tasks are lost work.", w=12),
                ),
            row("Caches",
                ts("Hit ratio by cache and level", [("%s / (%s + %s)" % (R("ha_cache_hits_total", "cache_type,level"), R("ha_cache_hits_total", "cache_type,level"), R("ha_cache_misses_total", "cache_type,level")), "{{cache_type}} {{level}}")], "percentunit", w=8),
                ts("Get latency p95 by level", [(P("ha_cache_get_latency_seconds", 0.95, "level"), "{{level}}")], "s", "Targets: L1 under 100 ns, L2 under 2 ms.", w=8),
                ts("Invalidations / locks", [(R("ha_cache_invalidations_total", "cache_type,source"), "invalidated {{cache_type}} {{source}}"), (R("ha_cache_lock_acquisitions_total", "result"), "lock {{result}}")], "short", w=8),
                ts("Orchestrator refreshes", [(R("ha_cache_orchestrator_refreshes_total", "result"), "{{result}}"), (P("ha_cache_orchestrator_refresh_duration_seconds", 0.95), "p95 s")], "short", w=8),
                ts("Chain queries", [(R("ha_cache_chain_queries_total", "query_type"), "{{query_type}}"), (R("ha_cache_chain_query_errors_total", "query_type"), "error {{query_type}}"),
                    (P("ha_cache_chain_query_latency_seconds", 0.95, "query_type"), "p95 s {{query_type}}")], "short", w=8),
                ts("Query client caches", [(R("ha_query_cache_hits_total", "client,cache_type"), "hit {{client}} {{cache_type}}"), (R("ha_query_cache_misses_total", "client,cache_type"), "miss {{client}} {{cache_type}}"),
                    (G("ha_query_cache_size", "max", "client,cache_type"), "size {{client}} {{cache_type}}")], "short", w=8),
                ts("gRPC stream queue p95", [(P("ha_grpc_stream_queue_seconds", 0.95, "conn"), "{{conn}}")], "s", w=12),
                ts("Panics recovered / log messages dropped", [(R("ha_panic_recoveries_total", "component"), "panic {{component}}"), (R("ha_log_messages_dropped_total"), "log messages dropped")], "short",
                   "Both stay at 0.", w=12),
                ),
        ],
    }
    return [money, pipeline, flow, relayer, storage, chain, internals]
